// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"EnemyProgressBar","status":true,"description":"Enemy HP Progress Bar that ends battle when full","parameters":{}},
{"name":"NRP_EventCollisionEX","status":true,"description":"v1.04 Extends the collision detection for events.","parameters":{"ConsiderEventMove":"true","SettingList":"[]"}}
];
